package com.cr.constant;

public enum Queue {

    SIMPLE_QUEUE,
    WORK_QUEUE,
    PUBLISH_SUBSCRIBE_QUEUE_1,
    PUBLISH_SUBSCRIBE_QUEUE_2,
    ROUTING_QUEUE_1,
    ROUTING_QUEUE_2,
    TOPICS_QUEUE_1,
    TOPICS_QUEUE_2,
    CONFIRM_ONE_QUEUE,
    CONFIRM_MULT_QUEUE,
    ASYN_CONFIRM_QUEUE,

}
