package com.cr;

public enum Queue {

    SIMPLE_QUEUE,
    WORK_ROUND_ROBIN_QUEUE,
    WORK_FAIR_DISPATCH_QUEUE,
    PUBLISH_SUBSCRIBE_QUEUE_1,
    PUBLISH_SUBSCRIBE_QUEUE_2,
    ROUTING_QUEUE_1,
    ROUTING_QUEUE_2,
    TOPICS_QUEUE_1,
    TOPICS_QUEUE_2,
}
