spring:
  rabbitmq:
    addresses: 127.0.0.1
    username: cr
    password: 123456
    virtual-host: /springboot
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 6549
    druid:
      initial-size: 5
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
mybatis:
  configuration:
    map-underscore-to-camel-case: true
