spring:
  rabbitmq:
    addresses: 127.0.0.1
    username: cr
    password: 123456
    virtual-host: /springboot
    publisher-returns: true
    publisher-confirms: true
  datasource:
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 6549
    druid:
      initial-size: 5
mybatis:
  configuration:
    map-underscore-to-camel-case: true